[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://time.areschang.top"
  to = "/time"
  status = 200
  force = true

[[redirects]]
  from = "https://clock.areschang.top/time"
  to = "https://time.areschang.top/time"
  status = 200
  force = true